colour:
  sma9: '#ffeb3b'
  sma4: '#5f3bff'
  rsi_line: '#ff00ff'
  rsi_30: '#ff0000'
  rsi_70: '#00ff00'
  stochastic_k_line: '#ff00ff'
  stochastic_d_line: '#00ffff'
  stochastic_80: '#ff0000'
  stochastic_20: '#00ff00'
  donchian_upper: '#00ff11'
  donchian_lower: '#ff4800'
  donchian_mean: '#ffffff'
  bollinger_upper: '#00fff2'
  bollinger_lower: '#ff0000'
  bollinger_mean: '#ffffff'